/* 
 This file was generated by Dashcode and is covered by the 
 license.txt included in the project.  You may edit this file, 
 however it is recommended to first turn off the Dashcode 
 code generator otherwise the changes will be lost.
 */
var dashcodePartSpecs = {
    "doneSave": { "creationFunction": "CreateButton", "leftImageWidth": 5, "onclick": "showFront", "rightImageWidth": 5, "text": "done", "view": "DC.View" },
    "download": { "creationFunction": "CreateButton", "leftImageWidth": 5, "onclick": "versionDownload", "rightImageWidth": 5, "text": "download", "view": "DC.View" },
    "drop": { "text": "drop", "view": "DC.Text" },
    "dropDetail": { "text": "dropDetail", "view": "DC.Text" },
    "failButton": { "creationFunction": "CreateButton", "leftImageWidth": 5, "onclick": "showMain", "rightImageWidth": 5, "text": "done", "view": "DC.View" },
    "failText": { "text": "fail", "view": "DC.Text" },
    "iaian7com": { "text": "iaian7com", "view": "DC.Text" },
    "image": { "view": "DC.ImageLayout" },
    "info": { "backgroundStyle": "black", "creationFunction": "CreateInfoButton", "foregroundStyle": "white", "frontID": "front", "onclick": "showBack", "view": "DC.View" },
    "locationText": { "text": "locationText", "view": "DC.Text" },
    "namingText": { "text": "namingText", "view": "DC.Text" },
    "new": { "text": "new", "view": "DC.Text" },
    "newVersion": { "text": "newVersion", "view": "DC.Text" },
    "overwrite": { "creationFunction": "CreatePopupButton", "leftImageWidth": 5, "name": "output", "onchange": "updateOverwrite", "options": [["never", "0"], ["always", "1"]], "rightImageWidth": 16, "view": "DC.View" },
    "overwriteText": { "text": "overwriteText", "view": "DC.Text" },
    "quality": { "creationFunction": "CreatePopupButton", "leftImageWidth": 5, "name": "scale", "onchange": "updateQuality", "options": [["1 (slow/best)", "1"], "2", ["3 (default)", "3"], "4", "5", "6", "7", "8", "9", ["10 (fast/rough)", "10"]], "rightImageWidth": 16, "view": "DC.View" },
    "qualityText": { "text": "qualityText", "view": "DC.Text" },
    "skip": { "creationFunction": "CreateButton", "leftImageWidth": 5, "onclick": "showMain", "rightImageWidth": 5, "text": "skip", "view": "DC.View" },
    "sliderBackground": { "creationFunction": "CreateShape", "leftImageWidth": 5, "rightImageWidth": 5 },
    "stack": { "subviewsTransitions": [{ "direction": "right-left", "duration": "", "timing": "ease-in-out", "type": "push" }, { "direction": "right-left", "duration": "", "timing": "ease-in-out", "type": "push" }, { "direction": "right-left", "duration": "", "timing": "ease-in-out", "type": "push" }, { "direction": "right-left", "duration": "", "timing": "ease-in-out", "type": "push" }, { "direction": "right-left", "duration": "", "timing": "ease-in-out", "type": "push" }], "view": "DC.StackLayout" },
    "successButton": { "creationFunction": "CreateButton", "leftImageWidth": 5, "onclick": "showMain", "rightImageWidth": 5, "text": "done", "view": "DC.View" },
    "successDetails": { "text": "successDetails", "view": "DC.Text" },
    "successText": { "text": "success", "view": "DC.Text" },
    "text": { "text": "copyrightText", "view": "DC.Text" },
    "wrongButton": { "creationFunction": "CreateButton", "leftImageWidth": 5, "onclick": "showMain", "rightImageWidth": 5, "text": "done", "view": "DC.View" },
    "wrongText": { "text": "wrong", "view": "DC.Text" }
};










