/* 
 This file was generated by Dashcode and is covered by the 
 license.txt included in the project.  You may edit this file, 
 however it is recommended to first turn off the Dashcode 
 code generator otherwise the changes will be lost.
 */
var localizedStrings = {
    "copyrightText": "©2012 John Einselen / Vectorform LLC",
    "done": "done",
    "download": "download",
    "drop": "drop image files here",
    "dropDetail": "24bit PNG only",
    "fail": "file processing failed\nplease try again",
    "failDetails": "make sure all selected files\nare valid PNG images",
    "iaian7com": "For more information,\niaian7.com/dashboard/crusher",
    "locationText": "PNGquant & posterizer",
    "nameDitherText": "if dithered",
    "nameFileText": "file sheet prefix",
    "nameIE6Text": "if ie6",
    "nameSpriteText": "%d = number of colors",
    "nameText": "colors = #",
    "namingText": "file name spacer",
    "new": "new update available!",
    "newVersion": "version number\nversion description",
    "outputText": "overwrite files",
    "overwriteText": "overwrite files",
    "qualityText": "quality versus speed",
    "scaleText": "quality speed",
    "skip": "skip version",
    "success": "file processing successful, busy compressing",
    "successDetails": "depending on image size\nthis could take a minute",
    "wrong": "wrong file format\nplease try again"
};











